// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFWvO2QgIxgVdHoFqSMSn3Lxpj91MJzNg',
    appId: '1:235124206131:web:c09065d10d0b3bf15a9146',
    messagingSenderId: '235124206131',
    projectId: 'cancer-scan',
    authDomain: 'cancer-scan.firebaseapp.com',
    storageBucket: 'cancer-scan.firebasestorage.app',
    measurementId: 'G-5HRRW053B1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8Ec3NJNshGMpmNsbuf8z3xuIeTgREIc4',
    appId: '1:235124206131:android:9e8fa0cac3df92c85a9146',
    messagingSenderId: '235124206131',
    projectId: 'cancer-scan',
    storageBucket: 'cancer-scan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-_PkyRtXrMsAQmF6RNi0ZxcJmmEfvHkA',
    appId: '1:235124206131:ios:b7702058893a28305a9146',
    messagingSenderId: '235124206131',
    projectId: 'cancer-scan',
    storageBucket: 'cancer-scan.firebasestorage.app',
    iosBundleId: 'com.example.canserScan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-_PkyRtXrMsAQmF6RNi0ZxcJmmEfvHkA',
    appId: '1:235124206131:ios:b7702058893a28305a9146',
    messagingSenderId: '235124206131',
    projectId: 'cancer-scan',
    storageBucket: 'cancer-scan.firebasestorage.app',
    iosBundleId: 'com.example.canserScan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFWvO2QgIxgVdHoFqSMSn3Lxpj91MJzNg',
    appId: '1:235124206131:web:b36395dab07835cb5a9146',
    messagingSenderId: '235124206131',
    projectId: 'cancer-scan',
    authDomain: 'cancer-scan.firebaseapp.com',
    storageBucket: 'cancer-scan.firebasestorage.app',
    measurementId: 'G-JJSFEZ4X6W',
  );
}
